export const fake_populars = [
  {
    backdrop_path: "/fEP2Sha3PXJnAcoGOjr5oybq44Q.jpg",
    first_air_date: "2023-05-08",
    genre_ids: [10765, 10759],
    id: 134224,
    name: "Voltes V: Legacy",
    origin_country: ["PH"],
    original_language: "tl",
    original_name: "Voltes V: Legacy",
    overview:
      "Voltes V: Legacy follows the story of three brothers, Steve, Big Bert, and Little Jon Armstrong, and their friends Jamie Robinson and Mark Gordon, as they fight the forces of humanoid aliens known as Boazanians who plans to invade the earth and launch their beast fighters all over the world.",
    popularity: 3251.893,
    poster_path: "/jZ32tdCTFsRoU2GehW6ZzSpTyS1.jpg",
    vote_average: 8,
    vote_count: 4,
  },
];

export const fake_recommendations = [
  {
    adult: false,
    backdrop_path: "/84XPpjGvxNyExjSuLQe0SzioErt.jpg",
    id: 1396,
    name: "Breaking Bad",
    original_language: "en",
    original_name: "Breaking Bad",
    overview:
      "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 301.725,
    first_air_date: "2008-01-20",
    vote_average: 8.882,
    vote_count: 11829,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/sccDflItNho4OiHkzpiDxB2fUFw.jpg",
    id: 1418,
    name: "The Big Bang Theory",
    original_language: "en",
    original_name: "The Big Bang Theory",
    overview:
      "The sitcom is centered on five characters living in Pasadena, California: roommates Leonard Hofstadter and Sheldon Cooper; Penny, a waitress and aspiring actress who lives across the hall; and Leonard and Sheldon's equally geeky and socially awkward friends and co-workers, mechanical engineer Howard Wolowitz and astrophysicist Raj Koothrappali. The geekiness and intellect of the four guys is contrasted for comic effect with Penny's social skills and common sense.",
    poster_path: "/ooBGRQBdbGzBxAVfExiO8r7kloA.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 145.085,
    first_air_date: "2007-09-24",
    vote_average: 7.879,
    vote_count: 10046,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    id: 66732,
    name: "Stranger Things",
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 9648],
    popularity: 242.651,
    first_air_date: "2016-07-15",
    vote_average: 8.631,
    vote_count: 15669,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/zymbuoBoL1i94xAOzVJF6IuWLfD.jpg",
    id: 77169,
    name: "Cobra Kai",
    original_language: "en",
    original_name: "Cobra Kai",
    overview:
      "This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.",
    poster_path: "/m7tG5E1EbywuwTsl6hq990So0Bx.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 35],
    popularity: 137.501,
    first_air_date: "2018-05-02",
    vote_average: 8.211,
    vote_count: 5612,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/85HCFXyCmvADwd3gJFyCz34CTAO.jpg",
    id: 100883,
    name: "Never Have I Ever",
    original_language: "en",
    original_name: "Never Have I Ever",
    overview:
      "After a traumatic year, all an Indian-American teen wants is to go from pariah to popular -- but friends, family and feeling won't make it easy on her.",
    poster_path: "/hd5fnBixab6IzfUwjC5wfdbX3eM.jpg",
    media_type: "tv",
    genre_ids: [35, 18],
    popularity: 537.386,
    first_air_date: "2020-04-27",
    vote_average: 8.2,
    vote_count: 1477,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/r7zUXadc1saFFSWz8lbUx7q9bkG.jpg",
    id: 1402,
    name: "The Walking Dead",
    original_language: "en",
    original_name: "The Walking Dead",
    overview:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
    poster_path: "/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 10765],
    popularity: 330.599,
    first_air_date: "2010-10-31",
    vote_average: 8.116,
    vote_count: 15032,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/uGy4DCmM33I7l86W7iCskNkvmLD.jpg",
    id: 60625,
    name: "Rick and Morty",
    original_language: "en",
    original_name: "Rick and Morty",
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    poster_path: "/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10765, 10759],
    popularity: 323.876,
    first_air_date: "2013-12-02",
    vote_average: 8.715,
    vote_count: 8285,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/q7XOgkp0NfjqVRYxzU0eGg7wSrm.jpg",
    id: 42009,
    name: "Black Mirror",
    original_language: "en",
    original_name: "Black Mirror",
    overview:
      "A contemporary British re-working of The Twilight Zone with stories that tap into the collective unease about our modern world. \n\nOver the last ten years, technology has transformed almost every aspect of our lives before we've had time to stop and question it. In every home; on every desk; in every palm - a plasma screen; a monitor; a smartphone - a black mirror of our 21st Century existence.",
    poster_path: "/5UaYsGZOFhjFDwQh6GuLjjA1WlF.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 9648],
    popularity: 277.431,
    first_air_date: "2011-12-04",
    vote_average: 8.314,
    vote_count: 4075,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/lerbYAaXFwNh0WpDEpYe5ba0SjK.jpg",
    id: 113988,
    name: "Dahmer – Monster: The Jeffrey Dahmer Story",
    original_language: "en",
    original_name: "Dahmer – Monster: The Jeffrey Dahmer Story",
    overview:
      "This series examines the gruesome and horrific true crimes of Jeffrey Dahmer and the systemic failures that enabled one of America’s most notorious serial killers to continue his murderous spree in plain sight for over a decade.",
    poster_path: "/f2PVrphK0u81ES256lw3oAZuF3x.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 72.021,
    first_air_date: "2022-09-21",
    vote_average: 8.088,
    vote_count: 2114,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/qSrSg6dZeZy6uJ6SfSKbEAwk3Wo.jpg",
    id: 58841,
    name: "Chicago P.D.",
    original_language: "en",
    original_name: "Chicago P.D.",
    overview:
      "A riveting police drama about the men and women of the Chicago Police Department's District 21 who put it all on the line to serve and protect their community. District 21 is made up of two distinctly different groups: the uniformed cops who patrol the beat and go head-to-head with the city's street crimes and the Intelligence Unit that combats the city's major offenses - organized crime, drug trafficking, high profile murders and beyond.",
    poster_path: "/7gtp4lusk685hdmuEXMbYrmSQoY.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 198.375,
    first_air_date: "2014-01-08",
    vote_average: 8.446,
    vote_count: 2114,
    origin_country: ["US"],
  },
];
